CREATE DATABASE SUCOS;
USE SUCOS;

/*########TABELA DE CLIENTES########*/
CREATE TABLE tbCliente 
(CPF VARCHAR(11) NOT NULL,
NOME VARCHAR(50) NOT NULL,
ENDERECO1 VARCHAR(150) NOT NULL,
ENDERECO2 VARCHAR(150) NOT NULL,
BAIRRO VARCHAR(50) NOT NULL,
CIDADE VARCHAR(50) NOT NULL,
ESTADO VARCHAR(50) NOT NULL,
CEP VARCHAR(8) NOT NULL,
IDADE SMALLINT NOT NULL,
SEXO VARCHAR(1) NOT NULL,
LIMITE_CREDITO FLOAT NOT NULL,
VOLUME_COMPRO FLOAT NOT NULL,
PRIMEIRA_COMPRA BIT(1)NOT NULL
);

DROP TABLE tbCliente;

ALTER TABLE tbCliente ADD PRIMARY KEY (CPF);
ALTER TABLE tbCliente ADD COLUMN(DATA_NASCIMENTO DATE);

INSERT INTO tbCliente (
CPF,
NOME,
ENDERECO1,
ENDERECO2,
BAIRRO,
CIDADE,
ESTADO,
CEP,
IDADE,
SEXO,
LIMITE_CREDITO,
VOLUME_COMPRO,
PRIMEIRA_COMPRA,
DATA_NASCIMENTO)
VALUES ('12345678911','Juca dos Santos','Rua Pojetada a numero 15',
'Rua Projetada a numero 14','Centro','Sao Paulo','Sao Paulo','15324869',22,'M',5000.00,2000,0,'2000-02-10');

SELECT * FROM tbCliente;


/*########TABELA DE VENDEDORES########*/
CREATE TABLE TBVENDEDORES (
MATRICULA varchar(5) NOT NULL, 
NOME varchar(100) NOT NULL, 
PERCENTUAL_COMISSAO float NOT NULL
);

INSERT INTO TBVENDEDORES(
MATRICULA,
NOME,
PERCENTUAL_COMISSAO)
VALUES("00233","João Geraldo da Fonseca",0.1);
INSERT INTO TBVENDEDORES(
MATRICULA,
NOME,
PERCENTUAL_COMISSAO)
VALUES("00235","Marcia Almeida",0.8);
INSERT INTO TBVENDEDORES(
MATRICULA,
NOME,
PERCENTUAL_COMISSAO)
VALUES("00236","Claudia",0.8);
INSERT INTO TBVENDEDORES(
MATRICULA,
NOME,
PERCENTUAL_COMISSAO)
VALUES("00236","Claudia",0.8);
INSERT INTO TBVENDEDORES(
MATRICULA,
NOME,
PERCENTUAL_COMISSAO,
DATA_ADMISSAO,
DE_FERIAS)
VALUES("00237","Roberta Martins ",1.1,"2017-03-18",1);
INSERT INTO TBVENDEDORES(
MATRICULA,
NOME,
PERCENTUAL_COMISSAO,
DATA_ADMISSAO,
DE_FERIAS)
VALUES("00238","Pericles Alves ",1.1,"2016-08-18",0);

UPDATE TBVENDEDORES SET PERCENTUAL_COMISSAO = 1.1,NOME = "Claudia Morais" WHERE MATRICULA = '00236';
UPDATE TBVENDEDORES SET NOME = "José Geraldo da Fonceca Junior" WHERE MATRICULA = '00233';

UPDATE TBVENDEDORES SET DATA_ADMISSAO = '2013-09-17', DE_FERIAS= 0 WHERE MATRICULA = '00236';
UPDATE TBVENDEDORES SET DATA_ADMISSAO = '2014-08-15', DE_FERIAS= 0 WHERE MATRICULA = '00235';

DELETE FROM TBVENDEDORES WHERE MATRICULA = "00233";

ALTER TABLE TBVENDEDORES ADD PRIMARY KEY(MATRICULA);
ALTER TABLE TBVENDEDORES ADD COLUMN (DATA_ADMISSAO DATE,DE_FERIAS BIT(1) NOT NULL);

SELECT * FROM TBVENDEDORES;

/*########TABELA DE PRODUTOS########*/
CREATE TABLE TBPRODUTO(
  PRODUTO VARCHAR(45) NOT NULL,
  NOME VARCHAR(150) NOT NULL,
  EMBALAGEM VARCHAR(50) NOT NULL,
  TAMANHO VARCHAR(50) NOT NULL,
  SABOR VARCHAR(50) NOT NULL,
  PRECO_LISTA FLOAT NOT NULL);

DROP TABLE TBPRODUTO;

INSERT INTO TBPRODUTO (
PRODUTO,
NOME,
EMBALAGEM,
TAMANHO,
SABOR,
PRECO_LISTA)
VALUES ("1050736","LIGHT - 350ML - LARANJA","LATA","350ML","MELANCIA",4.99);
INSERT INTO TBPRODUTO (
PRODUTO,NOME,EMBALAGEM,TAMANHO,SABOR,PRECO_LISTA)
VALUES ("1037815","Clean - 2LITROS - UVA","PET","2LITROS","UVA",16.99);
INSERT INTO TBPRODUTO (
PRODUTO,NOME,EMBALAGEM,TAMANHO,SABOR,PRECO_LISTA)
VALUES ("1045627","Sabor da Montanha - Limao","Garrafa","700ml","Limao",7.50);
INSERT INTO TBPRODUTO (
PRODUTO,NOME,EMBALAGEM,TAMANHO,SABOR,PRECO_LISTA)
VALUES ("12357226","Videira do Campo - 1.5 LITROS - Melancia","PET","1.5LITROS","Melancia",19.50);

UPDATE TBPRODUTO SET EMBALAGEM = 'LATA',TAMANHO ='1LITRO ' WHERE PRODUTO = "1045627";

DELETE FROM TBPRODUTO WHERE PRODUTO = "1037815";

ALTER TABLE TBPRODUTO ADD PRIMARY KEY(PRODUTO);

SELECT * FROM TBPRODUTO;


